//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db7e70c0cf078247eab177a5b0012f25efEntities : DbContext
    {
        public db7e70c0cf078247eab177a5b0012f25efEntities()
            : base("name=db7e70c0cf078247eab177a5b0012f25efEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbDados> tbDados { get; set; }
    }
}
